version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config/prometheus.yml:/prometheus/config/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus/prometheus_data
    command:
      - '--config.file=/prometheus/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/prometheus_data'
      - '--storage.tsdb.retention.size=1024MB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/config/grafana.ini:/grafana/config/grafana.ini
      - ./grafana/grafana_data:/grafana/grafana_data
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    command: 
      - '--config=/grafana/config/grafana.ini'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
