global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'minecraft'
    scrape_interval: 1s
    static_configs:
      - targets: ['mc_hub:9225']
        labels:
          server_name: 'hub'
      - targets: ['mc_survival:9225']
        labels:
          server_name: 'survival'
